#========================================================================================================================
# Description: Build Armbian For Amlogic S9xxx STB
# Copyright (C) 2021 https://github.com/ophub/amlogic-s9xxx-armbian
#========================================================================================================================

name: Rebuild armbian

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      armbian_url:
        description: "Enter armbian path"
        required: false
        default: ""

env:
  UPLOAD_FIRMWARE: false
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install $(curl -fsSL git.io/ubuntu-2004-server)
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean
          sudo timedatectl set-timezone "$TZ"
          sudo mkdir -p /workdir
          sudo chown $USER:$GROUPS /workdir
          if  [[ -n "${{ github.event.inputs.armbian_url }}" ]]; then
              armbian_url="${{ github.event.inputs.armbian_url }}"
          else
              armbian_down="https://armbian.tnahosting.net/dl/lepotato/archive/"
              armbian_file=$(curl -s ${armbian_down} | grep -oE Armbian.*buster.*.img.xz | head -n 1)
              if [ -n "${armbian_file}" ]; then
                  armbian_url="${armbian_down}/${armbian_file}"
              else
                  echo -e "Invalid download path: [ ${armbian_down} ]"
                  exit 1
              fi
          fi
          echo "ARMBIAN_URL=${armbian_url}" >> $GITHUB_ENV
          echo "COMPILE_STARTINGTIME=$(date +"%Y.%m.%d.%H%M")" >> $GITHUB_ENV

      - name: Rebuild Armbian for Amlogic s9xxx
        uses: ophub/amlogic-s9xxx-armbian@main
        with:
          armbian_path: ${{ env.ARMBIAN_URL }}
          armbian_soc: s905d_s905x3
          armbian_kernel: 5.10.80_5.4.160

      - name: Upload Armbian image to Actions
        uses: kittaakos/upload-artifact-as-is@master
        if: env.PACKAGED_STATUS == 'success' && env.UPLOAD_FIRMWARE == 'true' && !cancelled()
        with:
          path: ${{ env.PACKAGED_OUTPUTPATH }}/

      - name: Upload Armbian image to Release
        id: release
        uses: ncipollo/release-action@v1
        if: env.PACKAGED_STATUS == 'success' && env.UPLOAD_RELEASE == 'true' && !cancelled()
        with:
          tag: Armbian_Aml_${{ env.PACKAGED_OUTPUTDATE }}
          artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            This is Armbian image for amlogic s9xxx STB
            * Firmware information
            Default username: root
            Default password: 1234
            Install to EMMC command: armbian-install
            Update command: armbian-update
